const daisyuiColorObj = require("daisyui/src/theming/index");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./renderer/pages/**/*.{js,ts,jsx,tsx}",
    "./renderer/components/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    ...[...Array(101).keys()].flatMap((index) => [
      `group-hover:scale-[${index * 10}%]`,
      `group-hover:scale-[${index * 10}%]`,
    ]),
  ],
  prefix: "",
  theme: {
    extend: {
      animation: {
        marquee: "marquee 25s linear infinite",
        marquee2: "marquee2 25s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        marquee2: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0%)" },
        },
      },
      container: {
        center: true,
        padding: "2rem",
        screens: {
          "2xl": "1400px",
        },
      },
      spacing: {
        128: "28rem",
      },
      colors: {
        border: daisyuiColorObj["primary"],
        input: daisyuiColorObj["base-content"],
        ring: daisyuiColorObj["base-content"],
        background: daisyuiColorObj["base-100"],
        foreground: daisyuiColorObj["base-content"],
        primary: {
          DEFAULT: daisyuiColorObj["primary"],
          foreground: daisyuiColorObj["primary-content"],
        },
        secondary: {
          DEFAULT: daisyuiColorObj["secondary"],
          foreground: daisyuiColorObj["secondary-content"],
        },
        destructive: {
          DEFAULT: daisyuiColorObj["error"],
          foreground: daisyuiColorObj["error-content"],
        },
        muted: {
          DEFAULT: daisyuiColorObj["base-300"],
          foreground: daisyuiColorObj["base-content"],
        },
        accent: {
          DEFAULT: daisyuiColorObj["accent"],
          foreground: daisyuiColorObj["accent-content"],
        },
        popover: {
          DEFAULT: daisyuiColorObj["base-100"],
          foreground: daisyuiColorObj["base-content"],
        },
        card: {
          DEFAULT: daisyuiColorObj["base-100"],
          foreground: daisyuiColorObj["base-content"],
        },
      },
      borderRadius: {
        lg: "var(--rounded-btn)",
        md: "calc(var(--rounded-btn) - 2px)",
        sm: "calc(var(--rounded-btn) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    require("daisyui"),
    require("tailwindcss-animate"),
    require("tailwind-scrollbar"),
    require("@tailwindcss/typography"),
  ],
  daisyui: {
    darkTheme: "rescayl",
    themes: [
      {
        rescayl: {
          primary: "#991b1b",
          secondary: "#b91c1c",
          accent: "#dc2626",
          neutral: "#2a2a2a",
          "base-100": "#1a1a1a",
          "base-200": "#141414",
          "base-300": "#0a0a0a",
          info: "#7dd3fc",
          success: "#4ade80",
          warning: "#fbbf24",
          error: "#f87171",
          "primary-content": "#fef2f2",
          "secondary-content": "#ffffff",
          "accent-content": "#ffffff",
          "neutral-content": "#a3a3a3",
          "base-content": "#e5e5e5",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        ocean: {
          primary: "#38bdf8",
          "primary-content": "#082f49",
          secondary: "#2dd4bf",
          "secondary-content": "#042f2e",
          accent: "#a78bfa",
          "accent-content": "#2e1065",
          neutral: "#1e293b",
          "neutral-content": "#cbd5e1",
          "base-100": "#0f172a",
          "base-200": "#0b1120",
          "base-300": "#060a17",
          "base-content": "#e2e8f0",
          info: "#7dd3fc",
          "info-content": "#082f49",
          success: "#4ade80",
          "success-content": "#052e16",
          warning: "#fbbf24",
          "warning-content": "#451a03",
          error: "#f87171",
          "error-content": "#450a0a",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        forest: {
          primary: "#34d399",
          "primary-content": "#022c22",
          secondary: "#a3e635",
          "secondary-content": "#1a2e05",
          accent: "#fbbf24",
          "accent-content": "#451a03",
          neutral: "#1c2a21",
          "neutral-content": "#d1dcd5",
          "base-100": "#101b16",
          "base-200": "#0b1410",
          "base-300": "#060d0a",
          "base-content": "#e7f0ea",
          info: "#67e8f9",
          "info-content": "#083344",
          success: "#4ade80",
          "success-content": "#052e16",
          warning: "#fde047",
          "warning-content": "#422006",
          error: "#fb7185",
          "error-content": "#4c0519",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        violet: {
          primary: "#c084fc",
          "primary-content": "#2e1065",
          secondary: "#f0abfc",
          "secondary-content": "#4a044e",
          accent: "#a5b4fc",
          "accent-content": "#1e1b4b",
          neutral: "#2a2140",
          "neutral-content": "#d8d0ea",
          "base-100": "#1a1130",
          "base-200": "#140c26",
          "base-300": "#0d0719",
          "base-content": "#ece9f6",
          info: "#93c5fd",
          "info-content": "#1e3a8a",
          success: "#86efac",
          "success-content": "#052e16",
          warning: "#fcd34d",
          "warning-content": "#422006",
          error: "#fda4af",
          "error-content": "#4c0519",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        ember: {
          primary: "#fb923c",
          "primary-content": "#431407",
          secondary: "#f472b6",
          "secondary-content": "#500724",
          accent: "#facc15",
          "accent-content": "#422006",
          neutral: "#292524",
          "neutral-content": "#e7e5e4",
          "base-100": "#201411",
          "base-200": "#180e0c",
          "base-300": "#0f0a09",
          "base-content": "#f5e9e2",
          info: "#7dd3fc",
          "info-content": "#082f49",
          success: "#4ade80",
          "success-content": "#052e16",
          warning: "#fbbf24",
          "warning-content": "#451a03",
          error: "#f87171",
          "error-content": "#450a0a",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        mocha: {
          primary: "#d6a26a",
          "primary-content": "#271505",
          secondary: "#c08457",
          "secondary-content": "#2a1608",
          accent: "#e2b35f",
          "accent-content": "#2a1a05",
          neutral: "#2a2119",
          "neutral-content": "#e3d9cd",
          "base-100": "#1e1611",
          "base-200": "#17110d",
          "base-300": "#0e0a08",
          "base-content": "#f0e7df",
          info: "#93c5fd",
          "info-content": "#1e3a8a",
          success: "#86efac",
          "success-content": "#052e16",
          warning: "#fcd34d",
          "warning-content": "#422006",
          error: "#fda4af",
          "error-content": "#4c0519",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      "synthwave",
      "dark",
      "halloween",
      {
        alpine: {
          primary: "#1d4ed8",
          "primary-content": "#f8fafc",
          secondary: "#0e7490",
          "secondary-content": "#ffffff",
          accent: "#6d28d9",
          "accent-content": "#ffffff",
          neutral: "#334155",
          "neutral-content": "#e9eef5",
          "base-100": "#f6f8fb",
          "base-200": "#edf1f7",
          "base-300": "#e1e7f0",
          "base-content": "#16202e",
          info: "#0369a1",
          "info-content": "#e0f2fe",
          success: "#15803d",
          "success-content": "#ffffff",
          warning: "#b45309",
          "warning-content": "#ffffff",
          error: "#b91c1c",
          "error-content": "#ffffff",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        dawn: {
          primary: "#92400e",
          "primary-content": "#fffbeb",
          secondary: "#9a3412",
          "secondary-content": "#fff7ed",
          accent: "#9f1239",
          "accent-content": "#fff1f2",
          neutral: "#57534e",
          "neutral-content": "#f5f5f4",
          "base-100": "#fdf7ee",
          "base-200": "#f8efdf",
          "base-300": "#f1e3ca",
          "base-content": "#2f2414",
          info: "#0c4a6e",
          "info-content": "#e0f2fe",
          success: "#14532d",
          "success-content": "#f0fdf4",
          warning: "#a16207",
          "warning-content": "#fefce8",
          error: "#7f1d1d",
          "error-content": "#fef2f2",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        rose: {
          primary: "#be123c",
          "primary-content": "#fff1f2",
          secondary: "#9d174d",
          "secondary-content": "#fdf2f8",
          accent: "#6b21a8",
          "accent-content": "#faf5ff",
          neutral: "#4c1d2b",
          "neutral-content": "#fbe9ef",
          "base-100": "#fdf1f4",
          "base-200": "#f9e3ea",
          "base-300": "#f3d0dc",
          "base-content": "#431a26",
          info: "#0e7490",
          "info-content": "#ecfeff",
          success: "#15803d",
          "success-content": "#f0fdf4",
          warning: "#a16207",
          "warning-content": "#fefce8",
          error: "#b91c1c",
          "error-content": "#fef2f2",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        sage: {
          primary: "#166534",
          "primary-content": "#f0fdf4",
          secondary: "#365314",
          "secondary-content": "#f7fee7",
          accent: "#115e59",
          "accent-content": "#f0fdfa",
          neutral: "#3f5a4a",
          "neutral-content": "#eef4ef",
          "base-100": "#f2f7f3",
          "base-200": "#e6efe9",
          "base-300": "#d7e5dc",
          "base-content": "#1c2b22",
          info: "#155e75",
          "info-content": "#ecfeff",
          success: "#166534",
          "success-content": "#f0fdf4",
          warning: "#854d0e",
          "warning-content": "#fefce8",
          error: "#991b1b",
          "error-content": "#fef2f2",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
      {
        sky: {
          primary: "#1d4ed8",
          "primary-content": "#eff6ff",
          secondary: "#075985",
          "secondary-content": "#e0f2fe",
          accent: "#6d28d9",
          "accent-content": "#f5f3ff",
          neutral: "#3b4a63",
          "neutral-content": "#eaf1f8",
          "base-100": "#eef6fd",
          "base-200": "#e2eef9",
          "base-300": "#d0e3f4",
          "base-content": "#16263b",
          info: "#075985",
          "info-content": "#e0f2fe",
          success: "#166534",
          "success-content": "#f0fdf4",
          warning: "#a16207",
          "warning-content": "#fefce8",
          error: "#b91c1c",
          "error-content": "#fef2f2",
          "--rounded-btn": "1.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.4s",
          "--animation-input": "0.4s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
    ],
  },
};

// @layer base {
//   :root {
//     --background: 0 0% 100%;
//     --foreground: 222.2 84% 4.9%;
//     --card: 0 0% 100%;
//     --card-foreground: 222.2 84% 4.9%;
//     --popover: 0 0% 100%;
//     --popover-foreground: 222.2 84% 4.9%;
//     --primary: 222.2 47.4% 11.2%;
//     --primary-foreground: 210 40% 98%;
//     --secondary: 210 40% 96.1%;
//     --secondary-foreground: 222.2 47.4% 11.2%;
//     --muted: 210 40% 96.1%;
//     --muted-foreground: 215.4 16.3% 46.9%;
//     --accent: 210 40% 96.1%;
//     --accent-foreground: 222.2 47.4% 11.2%;
//     --destructive: 0 84.2% 60.2%;
//     --destructive-foreground: 210 40% 98%;
//     --border: 214.3 31.8% 91.4%;
//     --input: 214.3 31.8% 91.4%;
//     --ring: 222.2 84% 4.9%;
//     --radius: 0.5rem;
//   }

//   .dark {
//     --background: 222.2 84% 4.9%;
//     --foreground: 210 40% 98%;
//     --card: 222.2 84% 4.9%;
//     --card-foreground: 210 40% 98%;
//     --popover: 222.2 84% 4.9%;
//     --popover-foreground: 210 40% 98%;
//     --primary: 210 40% 98%;
//     --primary-foreground: 222.2 47.4% 11.2%;
//     --secondary: 217.2 32.6% 17.5%;
//     --secondary-foreground: 210 40% 98%;
//     --muted: 217.2 32.6% 17.5%;
//     --muted-foreground: 215 20.2% 65.1%;
//     --accent: 217.2 32.6% 17.5%;
//     --accent-foreground: 210 40% 98%;
//     --destructive: 0 62.8% 30.6%;
//     --destructive-foreground: 210 40% 98%;
//     --border: 217.2 32.6% 17.5%;
//     --input: 217.2 32.6% 17.5%;
//     --ring: 212.7 26.8% 83.9;
//   }
// }
